# -*- coding: utf-8 -*-
"""rozřazovačtřída.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykFWTjNLjHaUnolnmcO4WvFVsAT2mTEk
"""

import random
import pandas as pd
names = [
    "Karel B.",
    "Bára B.",
    "Vendula B.",
    "Barbora B.",
    "Elen B.",
    "Marie Elli B.",
    "Alex D.",
    "Nikola F.",
    "Viola F.",
    "Štěpán F.",
    "Sandra G.",
    "Eliška K.",
    "Daniel K.",
    "Čeněk K.",
    "Veronika K",
    "Bohumil K.",
    "Miroslav M.",
    "Jan N.",
    "Fabio P.",
    "Ella P.",
    "Daniela P.",
    "David R.",
    "Nela S.",
    "Patrik S.",
    "Adéla T.",
    "Eliška T.",
    "Jiří V.",
    "Markéta V.",
    "Klárka Z.",
    "Martin Ž."
]
services = ["Tabule", "Pomůcky", "Květiny", "Energie", "Úklid", ]
def assign_services(names, services):
    random.shuffle(names)
    assignments = {service: [] for service in services}

    for service in services:

        for _ in range(2):
            student = names.pop()
            assignments[service].append(student)

    return assignments


service_assignments = assign_services(names, services)


assignments_df = pd.DataFrame.from_dict(service_assignments, orient='index', columns=['Student 1', 'Student 2' ])


print(assignments_df)